# This workflow handles updating the table of contents, currently a calendar, on the README.
name: Generate README.md Calendar Table of Contents

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'

permissions:
  contents: write

jobs:
  update-readme-toc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f pyproject.toml ]; then
        pip install $(python -c '
        import tomllib
        print(
            " ".join(
                tomllib.load(open("pyproject.toml", "rb"))["tool"]["hatch"]["envs"][
                    "boilerplate"
                ]["dependencies"]
            )
        )
        ')
        else
        echo "Missing pyproject.toml"
        exit 1
        fi
    - name: Update README, add calendar TOC
      run: |
        python -m generate_calendar_toc
    - name: Commit new files
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit --author "Joseph Chiocchi <joe@yolk.cc>" -m "Update README.md, revise TOC"
        git push